version: '3.1'
networks:
  frontend:
    external: true
    name: npm_frontend
  backend:
    external: true
    name: npm_backend
  # main:
  #   external: true
  #   name: npm_main



services:

  landing_wordpress:
    container_name: vib_home
    image: wordpress
    restart: always
    ports:
      - 5090:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: 'Gp8Ajj4BmjXK6hq'
      WORDPRESS_DB_PASSWORD: 'X9dZFKCJKLZ8acH'
      WORDPRESS_DB_NAME: vibrant
      WORDPRESS_TABLE_PREFIX: 'landing_'
      WORDPRESS_AUTH_KEY:         'WK(XK:*^CS.[bRz6/ur|&V+l7[Dy9Bg.QBsutc%/v5jx1p}P^))f.{Vj%K+x(HbI'
      WORDPRESS_SECURE_AUTH_KEY:  '~pO+.ktwwq<7=|z%y^~:S0tWI=L}DC[h|+5 Jb1d%$<k^7>=^DMMAzn?.rDA<I}^'
      WORDPRESS_LOGGED_IN_KEY:    'SD6+~7l02u5AI[1.n?&f3^S,>it,2xi)4jg*k&[-3YiQgF7F<Pb=m|Ga5R&w[@^w'
      WORDPRESS_NONCE_KEY:        '![a~ECE# |H]P0]l+fVXk*V%f|f@suB3E)-+r7Vwo2f(HQ`U87Z79Hc*tu.tC+($'
      WORDPRESS_AUTH_SALT:        'SnX18AytTW^e1,3<8Xd6l1xk=>#xoY~Q[zg*xIaV4DGJy!S>cg7_vukqZ4=@qxL+'
      WORDPRESS_SECURE_AUTH_SALT: 'B~!Czyl|R`s$QX^p=,+KcqgV1B-?$D`KX5H{_lx<Q*Sc]>+kPAK4F(}4H*BjW4[s'
      WORDPRESS_LOGGED_IN_SALT:   '@#@31BZ-5g<t:aZr[@%(k/1/pKr7EaJQ/OLebjPIfokZuc)RN1Lw,&!2?5:Zq`Ea'
      WORDPRESS_NONCE_SALT:       'ls| z%TEiAz#H<[2]2HPj=y5g1,[Xt3!T*lro3!Y6uvcVMsl3:]O f42|I@Fc|MJ'
      WORDPRESS_CONFIG_EXTRA: 
        # define('CUSTOM_USER_TABLE', 'landing_users');
        # define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
        # define( 'COOKIE_DOMAIN', 'srd-test.ml' ); 
        # define( 'COOKIEHASH', md5( 'http://srd-test.ml' ) ); 
        # define( ‘ADMIN_COOKIE_PATH’, ‘/’ );
        # define( ‘COOKIEPATH’, ‘/’ );
        # define( ‘SITECOOKIEPATH’, ‘/’ );
    volumes:  
     - vib_landing:/var/www/html
    # - ./html:/var/www/html/
    networks:
      - frontend
      - backend


  # cnc_wordpress:
  #   image: wordpress
  #   restart: always
  #   ports:
  #     - 8092:80
  #   environment:
  #     WORDPRESS_DB_HOST: db_skydom
  #     WORDPRESS_DB_USER: Gp8Ajj4BmjXK6hq
  #     WORDPRESS_DB_PASSWORD: X9dZFKCJKLZ8acH
  #     WORDPRESS_DB_NAME: vibrant
  #     WORDPRESS_TABLE_PREFIX: cnc_
  #     WORDPRESS_AUTH_KEY:         '?+ sY.Shz8I()q(X.Nl)we1_V9$$cV,unQ _Bs;Q_An:(Yu~SGmJnUDG8_yI#KGJ'
  #     WORDPRESS_SECURE_AUTH_KEY:  '}SB*[W&M*WdU#S1sviFkb8t(Hjl xFXDiV]pS)31;XJv}p.Z-uta&!G-cBDO Xl3'
  #     WORDPRESS_LOGGED_IN_KEY:    'tU?qcuhibwOJQi-|s=b `;%U?+pFWiV5-mZO|*2-er~GQ*CkAhgdmqt.2my![:p0'
  #     WORDPRESS_NONCE_KEY:        'PjA.ts+TD@dA*dP`RL824YjpOiK7t03)V)_jI70+6/slA:c5rD<sAohMSdc(`1q7'
  #     WORDPRESS_AUTH_SALT:        'rc,,`rdbiK&GS=:{}wTv0,kxP9iCX;PiZRePM,gYU1em54{r@aEmgB4Ejw,SYENk'
  #     WORDPRESS_SECURE_AUTH_SALT: 'tQ8S,WImT:.7!|5>-VArU{+f[H;}ahsyb-%njcpPfn={!X? o7EWaf_v]N .HH%R'
  #     WORDPRESS_LOGGED_IN_SALT:   '&/>OkR4rn%*k.AQZ-b?QJ-74{p8vpMuD~+OjoJJ=iS2Dw;m+{BAA_61 9J]?lf>7'
  #     WORDPRESS_NONCE_SALT:       'D{S`NvAIQ|V)U:vWU)~k>]mI]VMpC(>K[nq^t|pfWzq:[13oA%Opp4k)]y>BCu!'
  #     WORDPRESS_CONFIG_EXTRA: 
  #       # define('CUSTOM_USER_TABLE', 'landing_users');
  #       # define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
  #       # define( 'COOKIE_DOMAIN', 'srd-test.ml' ); 
  #       # define( 'COOKIEHASH', md5( 'http://srd-test.ml' ) ); 
  #       # define( ‘ADMIN_COOKIE_PATH’, ‘/’ );
  #       # define( ‘COOKIEPATH’, ‘/’ );
  #       # define( ‘SITECOOKIEPATH’, ‘/’ );
  #   volumes:
  #     - cnc:/var/www/html
  #   # - ./html:/var/www/html/
  #   networks:
  #     - frontend
  #     - backend


  shop_wordpress:
    container_name: vib_shop
    image: wordpress
    restart: always
    ports:
      - 5094:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: 'Gp8Ajj4BmjXK6hq'
      WORDPRESS_DB_PASSWORD: 'X9dZFKCJKLZ8acH'
      WORDPRESS_DB_NAME: vibrant
      WORDPRESS_TABLE_PREFIX: shop_
      WORDPRESS_AUTH_KEY:         'WK(XK:*^CS.[bRz6/ur|&V+l7[Dy9Bg.QBsutc%/v5jx1p}P^))f.{Vj%K+x(HbI'
      WORDPRESS_SECURE_AUTH_KEY:  '~pO+.ktwwq<7=|z%y^~:S0tWI=L}DC[h|+5 Jb1d%$<k^7>=^DMMAzn?.rDA<I}^'
      WORDPRESS_LOGGED_IN_KEY:    'SD6+~7l02u5AI[1.n?&f3^S,>it,2xi)4jg*k&[-3YiQgF7F<Pb=m|Ga5R&w[@^w'
      WORDPRESS_NONCE_KEY:        '![a~ECE# |H]P0]l+fVXk*V%f|f@suB3E)-+r7Vwo2f(HQ`U87Z79Hc*tu.tC+($'
      WORDPRESS_AUTH_SALT:        'SnX18AytTW^e1,3<8Xd6l1xk=>#xoY~Q[zg*xIaV4DGJy!S>cg7_vukqZ4=@qxL+'
      WORDPRESS_SECURE_AUTH_SALT: 'B~!Czyl|R`s$QX^p=,+KcqgV1B-?$D`KX5H{_lx<Q*Sc]>+kPAK4F(}4H*BjW4[s'
      WORDPRESS_LOGGED_IN_SALT:   '@#@31BZ-5g<t:aZr[@%(k/1/pKr7EaJQ/OLebjPIfokZuc)RN1Lw,&!2?5:Zq`Ea'
      WORDPRESS_NONCE_SALT:       'ls| z%TEiAz#H<[2]2HPj=y5g1,[Xt3!T*lro3!Y6uvcVMsl3:]O f42|I@Fc|MJ'
      WORDPRESS_CONFIG_EXTRA: 
        # define('CUSTOM_USER_TABLE', 'landing_users');
        # define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
        # define( 'COOKIE_DOMAIN', 'srd-test.com' ); 
        # define( 'COOKIEHASH', md5( 'http://srd-test.ml' ) ); 
        # define( ‘ADMIN_COOKIE_PATH’, ‘/’ );
        # define( ‘COOKIEPATH’, ‘/’ );
        # define( ‘SITECOOKIEPATH’, ‘/’ );
    volumes:
      - vib_shop:/var/www/html
    # - ./html:/var/www/html/
    networks:
      - frontend
      - backend

  # learn_wordpress:
  #   image: wordpress
  #   restart: always
  #   ports:
  #     - 8096:80
  #   environment:
  #     WORDPRESS_DB_HOST: db_skydom
  #     WORDPRESS_DB_USER: Gp8Ajj4BmjXK6hq
  #     WORDPRESS_DB_PASSWORD: X9dZFKCJKLZ8acH
  #     WORDPRESS_DB_NAME: main
  #     WORDPRESS_TABLE_PREFIX: learn_
  #     WORDPRESS_AUTH_KEY:         '?+ sY.Shz8I()q(X.Nl)we1_V9$$cV,unQ _Bs;Q_An:(Yu~SGmJnUDG8_yI#KGJ'
  #     WORDPRESS_SECURE_AUTH_KEY:  '}SB*[W&M*WdU#S1sviFkb8t(Hjl xFXDiV]pS)31;XJv}p.Z-uta&!G-cBDO Xl3'
  #     WORDPRESS_LOGGED_IN_KEY:    'tU?qcuhibwOJQi-|s=b `;%U?+pFWiV5-mZO|*2-er~GQ*CkAhgdmqt.2my![:p0'
  #     WORDPRESS_NONCE_KEY:        'PjA.ts+TD@dA*dP`RL824YjpOiK7t03)V)_jI70+6/slA:c5rD<sAohMSdc(`1q7'
  #     WORDPRESS_AUTH_SALT:        'rc,,`rdbiK&GS=:{}wTv0,kxP9iCX;PiZRePM,gYU1em54{r@aEmgB4Ejw,SYENk'
  #     WORDPRESS_SECURE_AUTH_SALT: 'tQ8S,WImT:.7!|5>-VArU{+f[H;}ahsyb-%njcpPfn={!X? o7EWaf_v]N .HH%R'
  #     WORDPRESS_LOGGED_IN_SALT:   '&/>OkR4rn%*k.AQZ-b?QJ-74{p8vpMuD~+OjoJJ=iS2Dw;m+{BAA_61 9J]?lf>7'
  #     WORDPRESS_NONCE_SALT:       'D{S`NvAIQ|V)U:vWU)~k>]mI]VMpC(>K[nq^t|pfWzq:[13oA%Opp4k)]y>BCu!'
  #     WORDPRESS_CONFIG_EXTRA: 
  #       define('CUSTOM_USER_TABLE', 'landing_users');
  #       define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
  #   volumes:
  #     - learn:/var/www/html
  #   # - ./html:/var/www/html/
  #   networks:
  #     - frontend
  #     - backend


  # project_wordpress:
  #   image: wordpress
  #   restart: always
  #   ports:
  #     - 8098:80
  #   environment:
  #     WORDPRESS_DB_HOST: db_skydom
  #     WORDPRESS_DB_USER: Gp8Ajj4BmjXK6hq
  #     WORDPRESS_DB_PASSWORD: X9dZFKCJKLZ8acH
  #     WORDPRESS_DB_NAME: main
  #     WORDPRESS_TABLE_PREFIX: project_
  #     WORDPRESS_AUTH_KEY:         '?+ sY.Shz8I()q(X.Nl)we1_V9$$cV,unQ _Bs;Q_An:(Yu~SGmJnUDG8_yI#KGJ'
  #     WORDPRESS_SECURE_AUTH_KEY:  '}SB*[W&M*WdU#S1sviFkb8t(Hjl xFXDiV]pS)31;XJv}p.Z-uta&!G-cBDO Xl3'
  #     WORDPRESS_LOGGED_IN_KEY:    'tU?qcuhibwOJQi-|s=b `;%U?+pFWiV5-mZO|*2-er~GQ*CkAhgdmqt.2my![:p0'
  #     WORDPRESS_NONCE_KEY:        'PjA.ts+TD@dA*dP`RL824YjpOiK7t03)V)_jI70+6/slA:c5rD<sAohMSdc(`1q7'
  #     WORDPRESS_AUTH_SALT:        'rc,,`rdbiK&GS=:{}wTv0,kxP9iCX;PiZRePM,gYU1em54{r@aEmgB4Ejw,SYENk'
  #     WORDPRESS_SECURE_AUTH_SALT: 'tQ8S,WImT:.7!|5>-VArU{+f[H;}ahsyb-%njcpPfn={!X? o7EWaf_v]N .HH%R'
  #     WORDPRESS_LOGGED_IN_SALT:   '&/>OkR4rn%*k.AQZ-b?QJ-74{p8vpMuD~+OjoJJ=iS2Dw;m+{BAA_61 9J]?lf>7'
  #     WORDPRESS_NONCE_SALT:       'D{S`NvAIQ|V)U:vWU)~k>]mI]VMpC(>K[nq^t|pfWzq:[13oA%Opp4k)]y>BCu!'
  #     WORDPRESS_CONFIG_EXTRA: 
  #       define('CUSTOM_USER_TABLE', 'landing_users');
  #       define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
  #   volumes:
  #     - project:/var/www/html
  #   # - ./html:/var/www/html/
  #   networks:
  #     - frontend
  #     - backend


  # db_skydom:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: main
  #     MYSQL_USER: Gp8Ajj4BmjXK6hq
  #     MYSQL_PASSWORD: X9dZFKCJKLZ8acH
  #     MYSQL_ROOT_PASSWORD: ZdVtdA+vWMyJjHY3
  #   ports:
  #     - 3306
  #   volumes:
  #     - db_skydom:/var/lib/mysql
  #   networks:
  #     - backend
  

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   depends_on:
  #     - db_skydom
  #   environment:
  #     PMA_ARBITRARY: 1
  #   ports:
  #     - 8183:80
  #   networks:
  #     - backend
  #     - main



volumes:
  vib_landing:
  # cnc:
  vib_shop:
  #learn:
  #project:
  #db_skydom:



    # start with: docker-compose -f stack.yml up

    # copy files to PC 
    #docker cp wordpress-simple_landing_wordpress_1:/var/www/html Landing\  
    #docker cp wordpress-simple_project_wordpress_1:/var/www/html Project\  
    #docker cp wordpress-simple_learn_wordpress_1:/var/www/html Learn\  
    #docker cp wordpress-simple_shop_wordpress_1:/var/www/html Shop\ 
    #docker cp wordpress-simple_cnc_wordpress_1:/var/www/html CNC\  

   

