version: '3.1'

services:

  landing_wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
     - landing:/var/www/html
    # - ./html:/var/www/html/

  cnc_wordpress:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - cnc:/var/www/html
    # - ./html:/var/www/html/

  shop_wordpress:
    image: wordpress
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - shop:/var/www/html
    # - ./html:/var/www/html/

  learn_wordpress:
    image: wordpress
    restart: always
    ports:
      - 8083:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - learn:/var/www/html
    # - ./html:/var/www/html/

  project_wordpress:
    image: wordpress
    restart: always
    ports:
      - 8084:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - project:/var/www/html
    # - ./html:/var/www/html/



  db_skydom:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - 3306
    volumes:
      - db_skydom:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db_skydom
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8183:80

volumes:
  landing:
  cnc:
  shop:
  learn:
  project:
  db_skydom:
    # start with: docker-compose -f stack.yml up

    # copy files to PC 
    #docker cp wordpress-simple_landing_wordpress_1:/var/www/html Landing\  
    #docker cp wordpress-simple_project_wordpress_1:/var/www/html Project\  
    #docker cp wordpress-simple_learn_wordpress_1:/var/www/html Learn\  
    #docker cp wordpress-simple_shop_wordpress_1:/var/www/html Shop\ 
    #docker cp wordpress-simple_cnc_wordpress_1:/var/www/html CNC\   
    #