version: '3.1'
networks:
  frontend:
    external: true
  backend:
    external: true


services:

  RHS:
    image: wordpress
    container_name: RHS_WP
    restart: always
    ports:
      - 9080:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: "${DB_USER_NAME}"
      WORDPRESS_DB_PASSWORD: "${DB_USER_PASSWORD}"
      WORDPRESS_DB_NAME: "RHS"
    volumes:
      - wordpress:/var/www/html
    networks:
      - frontend
      - backend

  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: "${DB_NAME}"
  #     MYSQL_USER: "${DB_USER_NAME}"
  #     MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
  #     MYSQL_RANDOM_ROOT_PASSWORD: '1'
  #   volumes:
  #     - db:/var/lib/mysql

volumes:
  wordpress:
  # db: