version: '3.1'
networks:
  frontend:
    external: true
  backend:
    external: true


services:

  TacoHome:
    container_name: TacoHome
    image: wordpress
    restart: always
    ports:
      - 9070:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: "${DB_USER_NAME}"
      WORDPRESS_DB_PASSWORD: "${DB_USER_PASSWORD}"
      WORDPRESS_DB_NAME: "TacoHome"
      WORDPRESS_TABLE_PREFIX: "taco_"
      WORDPRESS_AUTH_KEY:         "${WP_AUTK}"
      WORDPRESS_SECURE_AUTH_KEY:  "${WP_SECK}"
      WORDPRESS_LOGGED_IN_KEY:    "${WP_LOGK}"
      WORDPRESS_NONCE_KEY:        "${WP_NONK}"
      WORDPRESS_AUTH_SALT:        "${WP_AUTS}"
      WORDPRESS_SECURE_AUTH_SALT: "${WP_SECS}"
      WORDPRESS_LOGGED_IN_SALT:   "${WP_LOGS}"
      WORDPRESS_NONCE_SALT:       "${WP_NONS}"
      WORDPRESS_CONFIG_EXTRA: 
        # define('CUSTOM_USER_TABLE', 'landing_users');
        # define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
        # define( 'COOKIE_DOMAIN', 'srd-test.ml' ); 
        # define( 'COOKIEHASH', md5( 'http://srd-test.ml' ) ); 
        # define( ‘ADMIN_COOKIE_PATH’, ‘/’ );
        # define( ‘COOKIEPATH’, ‘/’ );
        # define( ‘SITECOOKIEPATH’, ‘/’ );
    volumes:  
     - vib_sprouts:/var/www/html
     - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    # - ./html:/var/www/html/
    networks:
      - frontend
      - backend




volumes:
  vib_sprouts:



    # start with: docker-compose -f stack.yml up

    # copy files to PC 
    #docker cp wordpress-simple_landing_wordpress_1:/var/www/html Landing\  
    #docker cp wordpress-simple_project_wordpress_1:/var/www/html Project\  
    #docker cp wordpress-simple_learn_wordpress_1:/var/www/html Learn\  
    #docker cp wordpress-simple_shop_wordpress_1:/var/www/html Shop\ 
    #docker cp wordpress-simple_cnc_wordpress_1:/var/www/html CNC\  

   

