version: '3.1'
networks:
  frontend:
    external: true

  backend:
    external: true

  # main:
  #   external: true
  #   name: npm_main



services:

  landing_wordpress:
    image: wordpress
    restart: always
    container_name: skydom_home
    ports:
      - 9000:80
    environment:
      WORDPRESS_DB_HOST: db_skydom
      WORDPRESS_DB_USER: "${DB_USER_NAME}"
      WORDPRESS_DB_PASSWORD: "${DB_USER_PASSWORD}"
      WORDPRESS_DB_NAME: skydom
      WORDPRESS_TABLE_PREFIX: "landing_"
      WORDPRESS_AUTH_KEY:         "${WP_AUTK}"
      WORDPRESS_SECURE_AUTH_KEY:  "${WP_SECK}"
      WORDPRESS_LOGGED_IN_KEY:    "${WP_LOGK}"
      WORDPRESS_NONCE_KEY:        "${WP_NONK}"
      WORDPRESS_AUTH_SALT:        "${WP_AUTS}"
      WORDPRESS_SECURE_AUTH_SALT: "${WP_SECS}"
      WORDPRESS_LOGGED_IN_SALT:   "${WP_LOGS}"
      WORDPRESS_NONCE_SALT:       "${WP_NONS}"
      WORDPRESS_CONFIG_EXTRA: 
        # define('CUSTOM_USER_TABLE', 'landing_users');
        # define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
        # define( 'COOKIE_DOMAIN', 'srd-test.ml' ); 
        # define( 'COOKIEHASH', md5( 'http://srd-test.ml' ) ); 
        # define( ‘ADMIN_COOKIE_PATH’, ‘/’ );
        # define( ‘COOKIEPATH’, ‘/’ );
        # define( ‘SITECOOKIEPATH’, ‘/’ );
    volumes:  
     - landing:/var/www/html
     - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
     
    # - ./html:/var/www/html/
    networks:
      - frontend
      - backend


  # cnc_wordpress:
  #   image: wordpress
  #   restart: always
  #   ports:
  #     - 8092:80
  #   environment:
  #     WORDPRESS_DB_HOST: db_skydom
  #     WORDPRESS_DB_USER: "${DB_USER_NAME}"
  #     WORDPRESS_DB_PASSWORD: "${DB_USER_PASSWORD}"
  #     WORDPRESS_DB_NAME: skydom
  #     WORDPRESS_TABLE_PREFIX: cnc_
  #     WORDPRESS_AUTH_KEY:         "${WP_AUTK}"
  #     WORDPRESS_SECURE_AUTH_KEY:  "${WP_SECK}"
  #     WORDPRESS_LOGGED_IN_KEY:    "${WP_LOGK}"
  #     WORDPRESS_NONCE_KEY:        "${WP_NONK}"
  #     WORDPRESS_AUTH_SALT:        "${WP_AUTS}"
  #     WORDPRESS_SECURE_AUTH_SALT: "${WP_SECS}"
  #     WORDPRESS_LOGGED_IN_SALT:   "${WP_LOGS}"
  #     WORDPRESS_NONCE_SALT:       "${WP_NONS}"
  #     WORDPRESS_CONFIG_EXTRA: 
  #       # define('CUSTOM_USER_TABLE', 'landing_users');
  #       # define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
  #       # define( 'COOKIE_DOMAIN', 'srd-test.ml' ); 
  #       # define( 'COOKIEHASH', md5( 'http://srd-test.ml' ) ); 
  #       # define( ‘ADMIN_COOKIE_PATH’, ‘/’ );
  #       # define( ‘COOKIEPATH’, ‘/’ );
  #       # define( ‘SITECOOKIEPATH’, ‘/’ );
  #   volumes:
  #     - cnc:/var/www/html
  #   # - ./html:/var/www/html/
  #   networks:
  #     - frontend
  #     - backend


  # shop_wordpress:
  #   image: wordpress
  #   restart: always
  #   ports:
  #     - 8094:80
  #   environment:
  #     WORDPRESS_DB_HOST: db_skydom
  #     WORDPRESS_DB_USER: "${DB_USER_NAME}"
  #     WORDPRESS_DB_PASSWORD: "${DB_USER_PASSWORD}"
  #     WORDPRESS_DB_NAME: skydom
  #     WORDPRESS_TABLE_PREFIX: shop_
  #     WORDPRESS_AUTH_KEY:         "${WP_AUTK}"
  #     WORDPRESS_SECURE_AUTH_KEY:  "${WP_SECK}"
  #     WORDPRESS_LOGGED_IN_KEY:    "${WP_LOGK}"
  #     WORDPRESS_NONCE_KEY:        "${WP_NONK}"
  #     WORDPRESS_AUTH_SALT:        "${WP_AUTS}"
  #     WORDPRESS_SECURE_AUTH_SALT: "${WP_SECS}"
  #     WORDPRESS_LOGGED_IN_SALT:   "${WP_LOGS}"
  #     WORDPRESS_NONCE_SALT:       "${WP_NONS}"
  #     WORDPRESS_CONFIG_EXTRA: 
  #       # define('CUSTOM_USER_TABLE', 'landing_users');
  #       # define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
  #       # define( 'COOKIE_DOMAIN', 'srd-test.com' ); 
  #       # define( 'COOKIEHASH', md5( 'http://srd-test.ml' ) ); 
  #       # define( ‘ADMIN_COOKIE_PATH’, ‘/’ );
  #       # define( ‘COOKIEPATH’, ‘/’ );
  #       # define( ‘SITECOOKIEPATH’, ‘/’ );
  #   volumes:
  #     - shop:/var/www/html
  #   # - ./html:/var/www/html/
  #   networks:
  #     - frontend
  #     - backend

  # learn_wordpress:
  #   image: wordpress
  #   restart: always
  #   ports:
  #     - 8096:80
  #   environment:
      # WORDPRESS_DB_HOST: db_skydom
      # WORDPRESS_DB_USER: "${DB_USER_NAME}"
      # WORDPRESS_DB_PASSWORD: "${DB_USER_PASSWORD}"
      # WORDPRESS_DB_NAME: skydom
  #     WORDPRESS_TABLE_PREFIX: learn_
      # WORDPRESS_AUTH_KEY:         "${WP_AUTK}"
      # WORDPRESS_SECURE_AUTH_KEY:  "${WP_SECK}"
      # WORDPRESS_LOGGED_IN_KEY:    "${WP_LOGK}"
      # WORDPRESS_NONCE_KEY:        "${WP_NONK}"
      # WORDPRESS_AUTH_SALT:        "${WP_AUTS}"
      # WORDPRESS_SECURE_AUTH_SALT: "${WP_SECS}"
      # WORDPRESS_LOGGED_IN_SALT:   "${WP_LOGS}"
      # WORDPRESS_NONCE_SALT:       "${WP_NONS}"
  #     WORDPRESS_CONFIG_EXTRA: 
  #       define('CUSTOM_USER_TABLE', 'landing_users');
  #       define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
  #   volumes:
  #     - learn:/var/www/html
  #   # - ./html:/var/www/html/
  #   networks:
  #     - frontend
  #     - backend


  # project_wordpress:
  #   image: wordpress
  #   restart: always
  #   ports:
  #     - 8098:80
  #   environment:
  #     WORDPRESS_DB_HOST: db_skydom
  #     WORDPRESS_DB_USER: Gp8Ajj4BmjXK6hq
  #     WORDPRESS_DB_PASSWORD: X9dZFKCJKLZ8acH
  #     WORDPRESS_DB_NAME: main
  #     WORDPRESS_TABLE_PREFIX: project_
      # WORDPRESS_AUTH_KEY:         "${WP_AUTK}"
      # WORDPRESS_SECURE_AUTH_KEY:  "${WP_SECK}"
      # WORDPRESS_LOGGED_IN_KEY:    "${WP_LOGK}"
      # WORDPRESS_NONCE_KEY:        "${WP_NONK}"
      # WORDPRESS_AUTH_SALT:        "${WP_AUTS}"
      # WORDPRESS_SECURE_AUTH_SALT: "${WP_SECS}"
      # WORDPRESS_LOGGED_IN_SALT:   "${WP_LOGS}"
      # WORDPRESS_NONCE_SALT:       "${WP_NONS}"
  #     WORDPRESS_CONFIG_EXTRA: 
  #       define('CUSTOM_USER_TABLE', 'landing_users');
  #       define('CUSTOM_USERMETA_TABLE', 'landing_usermeta');
  #   volumes:
  #     - project:/var/www/html
  #   # - ./html:/var/www/html/
  #   networks:
  #     - frontend
  #     - backend


  # db_skydom:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: main
  #     MYSQL_USER: Gp8Ajj4BmjXK6hq
  #     MYSQL_PASSWORD: X9dZFKCJKLZ8acH
  #     MYSQL_ROOT_PASSWORD: ZdVtdA+vWMyJjHY3
  #   ports:
  #     - 3306
  #   volumes:
  #     - db_skydom:/var/lib/mysql
  #   networks:
  #     - backend
  

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   depends_on:
  #     - db_skydom
  #   environment:
  #     PMA_ARBITRARY: 1
  #   ports:
  #     - 8183:80
  #   networks:
  #     - backend
  #     - main



volumes:
  landing:
  # cnc:
  # shop:
  #learn:
  #project:
  #db_skydom:



    # start with: docker-compose -f stack.yml up

    # copy files to PC 
    #docker cp wordpress-simple_landing_wordpress_1:/var/www/html Landing\  
    #docker cp wordpress-simple_project_wordpress_1:/var/www/html Project\  
    #docker cp wordpress-simple_learn_wordpress_1:/var/www/html Learn\  
    #docker cp wordpress-simple_shop_wordpress_1:/var/www/html Shop\ 
    #docker cp wordpress-simple_cnc_wordpress_1:/var/www/html CNC\  

   

